<!DOCTYPE html>
<!--
Copyright (c) 2013 Samsung Electronics Co., Ltd.

Licensed under the Apache License, Version 2.0 (the License);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Authors:
        Krzysztof Lachacz <k.lachacz@samsung.com>

-->

<html>
<head>
<title>CallHistory_removeBatch_successCallback_undefined</title>
<script src="support/unitcommon.js"></script>
<script src="support/callcommon.js"></script>
</head>

<body>
<div id="log"></div>
<script type="text/javascript">
//==== TEST: CallHistory_removeBatch_successCallback_undefined
//==== LABEL Check whether removeBatch() method called with undefined successCallback throws exception
//==== EXECUTION_TYPE manual
//==== PRIORITY P2
//==== SPEC Tizen Web API:Social:Callhistory:CallHistory:removeBatch M
//==== SPEC_URL https://developer.tizen.org/help/topic/org.tizen.web.device.apireference/tizen/callhistory.html
//==== TEST_CRITERIA MC
//==== PRE Make at least 3 existence call history

setup({timeout: 90000});

var t = async_test(document.title, {timeout: 90000}),
    findSuccess, findError, removeBatchError, list, exceptionName = "TypeMismatchError";

t.step(function () {
    removeBatchError = t.step_func(function (error) {
        assert_unreached("removeBatch() error callback invoked: name: " + error.name + ", msg: " + error.message);
    });

    findError = t.step_func(function (error) {
        assert_unreached("find() error callback invoked: name: " + error.name + ", msg: " + error.message);
    });

    findSuccess = t.step_func(function (results) {
        assert_type(results, "array", "Results should be an array");
        assert_true(results.length > 2, "Expected 3 calls in history at least, but found: " + results.length);
        list = [results[0], results[1]];

        assert_throws({ name: exceptionName },
            function () {
                tizen.callhistory.removeBatch(list, undefined, removeBatchError);
            }, exceptionName + " should be thrown");

        t.done();
    });

    tizen.callhistory.find(findSuccess, findError);
});

</script>
</body>
</html>
